version: '3'

services:
  webapp:
    build: ./web-app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  mlc:
    build: ./machine-learning-client
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
